### ISSUE TITLE
Support diff of system derivation

### ISSUE THREAD

**Issue by danbst** [Gabriel439/nix-diff#10]
```
$ nix-diff /nix/store/lf3l0fn8lfllhm6kb1w5jlfdc181d29z-nixos-system-station-18.09.pre.5da8543.drv \
           /nix/store/7spzzxnkxg7w053m288vfvvbhaxd4lmx-nixos-system-station-18.09.pre.01b254e.drv
- /nix/store/lf3l0fn8lfllhm6kb1w5jlfdc181d29z-nixos-system-station-18.09.pre.5da8543.drv:{out}
+ /nix/store/7spzzxnkxg7w053m288vfvvbhaxd4lmx-nixos-system-station-18.09.pre.01b254e.drv:{out}
• The derivation names do not match
```
The workaround is to rename those derivations to s1.drv s2.drv and then `nix-diff s1.drv s2.drv`

**Comment by Gabriel439** [comment]
See: https://github.com/Gabriel439/nix-diff/issues/6

Based on that issue, I believe you can set `nixos.system.label` to a fixed string so that the derivation name is unaffected by the change in the `nixpkgs` revision

**Comment by bhipple** [comment]
Would you be willing to cut another release for this?  I happen to have a use case diffing versions of user environments and would like to be able to just install this without any overlays.  At the moment I'm using the `cp` and `nix-diff {s1,s2}.drv` workaround.

**Comment by Gabriel439** [comment]
@bhipple: Yeah, no problem!  I just uploaded this to Hackage as `nix-diff-1.0.3`
