### ISSUE TITLE
Color escape codes are restricted to tty output

### ISSUE THREAD

**Issue by Ekleog** [Gabriel439/nix-diff#13]
Counter-balance of https://github.com/Gabriel439/nix-diff/issues/1: when I run `nix-diff foo bar | less -R`, I don't get colors (even though `less -R` should proxy them out).

This may be fixed by adding a `--color=(never|auto|always)` command-line parameter.

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/Gabriel439/nix-diff/pull/14

Let me know if that works for you.  I added the flags `--color` and `--no-color` and the absence of the flag indicates to use automatic color detection

**Comment by Ekleog** [comment]
Sounds great, thanks! I unfortunately don't have a testbed available
right now.

BTW, the `--color=(always|auto|never)` option I proposed were picked
from the “standard” of `grep` / `rg` / `ls` and maybe others I can't
think of right now, but the choice of options is obviously yours, so
long as there are options it fits my use case.

Thank you! :D

**Comment by Gabriel439** [comment]
Alright, I'll match their option style

**Comment by Ekleog** [comment]
Great, thanks! I don't have a testing bed right now, do you want me to
test later and report here? I can't guarantee anything about delays,
though, currently being quite overwhelmed by various stuff.

**Comment by Gabriel439** [comment]
@Ekleog: No need.  I already tested it myself.  I just wanted you to review the user interface

**Comment by Ekleog** [comment]
Great, thank you! :D
