### ISSUE TITLE
character encoding error when running nix-diff

### ISSUE THREAD

**Issue by robinp** [Gabriel439/nix-diff#18]
Platform: linux + nixpkgs.
```
$ nix-shell -p nix-diff  # gets version 1.0.6
$ nix-diff /nix/store/b5fm7nd0c4bc6bldlpp4yyicpzdmk1b8-nixops-machines.drv  /nix/store/r97qpaipk0ylj385n00vylg82izizmmg-nixops-machines.drv --color never
nix-diff: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
```
Sounds like https://ghc.haskell.org/trac/ghc/ticket/8118.

**Comment by Gabriel439** [comment]
Pull request up here: https://github.com/Gabriel439/nix-diff/pull/19

Let me know if that branch fixes the problem for you

**Comment by robinp** [comment]
@Gabriel439 works as a charm! Thank you, for the tool as well.

**Comment by Gabriel439** [comment]
You're welcome! :slightly_smiling_face:
