### ISSUE TITLE
Optionally include diff of source content

### ISSUE THREAD

**Issue by terlar** [Gabriel439/nix-diff#29]
Often times I find derivations diffing due to sources, I always end up having to run `diff -r oldSource newSource` in order to figure out what is going on. Would be nice if this could be integrated into the tool.

Many thanks for an invaluable tool!

**Comment by Gabriel439** [comment]
@terlar: Can you clarify what you mean by source content?

**Comment by terlar** [comment]
I mean the content of the input sources, right now it looks like this:
```
          • The set of input sources do not match:
              - /nix/store/xzw6bqf6v5dci7qw10fpzvqq4w4vqn5p-openapi2erlang
              + /nix/store/05jwz6g7yq1g8gy0jgx4ci0jgwg8mdqq-openapi2erlang
          • The environments do not match:
              src=''
                  /nix/store/xz05jw6bqfz6v5dcig7yqw1g8gy0fpzvqqjgx4ci0jgw4vg8mdqn5pq-openapi2erlang
              ''
```

However it would be nice if I could see the diff of these two paths as well.

**Comment by Gabriel439** [comment]
@terlar: I have a fix for this up here: https://github.com/Gabriel439/nix-diff/pull/30

Could you give that a try and let me know if it addresses your use case?

**Comment by terlar** [comment]
I didn't see any difference, but perhaps I didn't build it correctly, I added an overlay like this, which I hope would be correct:
```
final: prev:

{
  nix-diff = prev.nix-diff.overrideAttrs (old: {
    src = prev.fetchFromGitHub {
      owner = "Gabriel439";
      repo = "nix-diff";
      rev = "e12ca3ac4b131334c8ffe9900905c5f01cb9b6cd";
      hash = "sha256-S4k8v+zBo9LwzaaSoyuYzWQW4p6G90pgy6HT0APW9Cw=";
    };
    buildInputs = old.buildInputs ++ [ final.haskellPackages.directory ];
  });
}
```

It seems the src was overridden correctly, since I checked the content. But I tried building with and without directory and both worked, so perhaps my override is not working properly?

I will take another look tomorrow to see if I can build the project individually, to ensure it is the latest.

**Comment by terlar** [comment]
Okay, I can verify that my overlay indeed worked, but also noticed the project had nix files (of course :sun_with_face:) and built it via those.

So what I see before this change:
```
              • The input named `ca-core-kondo` differs
                - /nix/store/hcjzqz1ssph764bcjksk5hsfiivx6fb2-ca-core-kondo.drv:{out}
                + /nix/store/iyz18jd33hvwljiqmqlr0x7jgxia79d5-ca-core-kondo.drv:{out}
                • The set of input sources do not match:
                    - /nix/store/wdl2qcynkqzmgnyzwwqnl4mzd8p8cyf4-source
                    + /nix/store/biybaxipskc4rp0bws3m2ml4rl36dw8a-source
                • The environments do not match:
                    srcs=''
                        /nix/store/wdl2qcbiynbaxipskqzmgnyzwc4rp0bwqns3m2ml4mzrl36d8pw8cyf4a-source
                    ''
```

What I see after:
```
              • The input derivation named `ca-core-kondo` differs
                - /nix/store/hcjzqz1ssph764bcjksk5hsfiivx6fb2-ca-core-kondo.drv:{out}
                + /nix/store/iyz18jd33hvwljiqmqlr0x7jgxia79d5-ca-core-kondo.drv:{out}
                • The input source named `source` differs
                • The environments do not match:
                    srcs=''
                    /nix/store/wdl2qcbiynbaxipskqzmgnyzwc4rp0bwqns3m2ml4mzrl36d8pw8cyf4a-source
                ''
```

Or is this something that requires `--environment`

**Comment by Gabriel439** [comment]
@terlar: Do the files `/nix/store/wdl2qcynkqzmgnyzwwqnl4mzd8p8cyf4-source` and `/nix/store/biybaxipskc4rp0bws3m2ml4rl36dw8a-source` exist?

**Comment by terlar** [comment]
Ah, good question, this was two old derivations, so it might have garbage collected. Sorry about that, I will make another check tomorrow with two fresh derivations. Unfortunately now I’m offline for today.

**Comment by terlar** [comment]
I now verified that the sources exists, but still experience the same thing:
```
λ nix-diff /nix/store/12h4lqrcirxc7841r5c993ii4xpc9l7a-kws-request-unset.drv /nix/store/jib4q2hhnbs34rm4vb3gsj2802iyw983-kws-request-unset.drv
- /nix/store/12h4lqrcirxc7841r5c993ii4xpc9l7a-kws-request-unset.drv:{out}
+ /nix/store/jib4q2hhnbs34rm4vb3gsj2802iyw983-kws-request-unset.drv:{out}
• The set of input sources do not match:
    - /nix/store/y4f2lgnmwyq0j12s0sgc6mx5prh2l0nz-src
    + /nix/store/fkn53dpdi140ckpnvfsdz7jl7j60lfbc-src
• The environments do not match:
    src=''
        /nix/store/y4f2lgknmwyq0j53dpdi12s40sgc6mx5kprh2l0nvfsdz7jl7j60lfbc-src
    ''
λ /nix/store/b7yifakl2dm22q1vbzazmslizlfl23qs-nix-diff-1.0.10/bin/nix-diff /nix/store/12h4lqrcirxc7841r5c993ii4xpc9l7a-kws-request-unset.drv /nix/store/jib4q2hhnbs34rm4vb3gsj2802iyw983-kws-request-unset.drv
- /nix/store/12h4lqrcirxc7841r5c993ii4xpc9l7a-kws-request-unset.drv:{out}
+ /nix/store/jib4q2hhnbs34rm4vb3gsj2802iyw983-kws-request-unset.drv:{out}
• The input source named `src` differs
• The environments do not match:
    src=''
    /nix/store/y4f2lgknmwyq0j53dpdi12s40sgc6mx5kprh2l0nvfsdz7jl7j60lfbc-src
''
λ file /nix/store/fkn53dpdi140ckpnvfsdz7jl7j60lfbc-src /nix/store/y4f2lgnmwyq0j12s0sgc6mx5prh2l0nz-src
/nix/store/fkn53dpdi140ckpnvfsdz7jl7j60lfbc-src: directory
/nix/store/y4f2lgnmwyq0j12s0sgc6mx5prh2l0nz-src: directory

λ diff -r /nix/store/fkn53dpdi140ckpnvfsdz7jl7j60lfbc-src /nix/store/y4f2lgnmwyq0j12s0sgc6mx5prh2l0nz-src
Only in /nix/store/y4f2lgnmwyq0j12s0sgc6mx5prh2l0nz-src: NOICE
```

**Comment by Gabriel439** [comment]
@terlar: Sorry for the delay.  I see what is happening now.  The reason that the branch still doesn't display a diff is because the two differing input sources are directories.  It only displays a diff if they are files.

**Comment by terlar** [comment]
@Gabriel439 Ah, I see, thank you. I guess it was not fully clear that the sources were directories, files are useful as well, but it is mostly common to have directories as sources. Do you think it would be possible to make the diff recursive?

**Comment by Gabriel439** [comment]
@terlar: Possibly, but I would like to stick just diffing files for now
